-- 코드를 입력하세요
SELECT DATE_FORMAT(U.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, U.PRODUCT_ID, U.USER_ID, U.SALES_AMOUNT
FROM (
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE) AS U
WHERE YEAR(U.SALES_DATE) = 2022 AND MONTH(U.SALES_DATE) = 03
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;